export const data = [
    {
        id: 1,
        name: "Alice Smith",
        email: "alice.smith@example.com",
        age: 28,
        isActive: true,
        phone: "123-456-7890",
        address: "123 Maple St, Springfield",
        registrationDate: new Date("2021-06-01"),
        lastLogin: new Date("2023-10-01"),
        role: "admin"
    },
    {
        id: 2,
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        age: 34,
        isActive: false,
        phone: "234-567-8901",
        address: "456 Oak St, Springfield",
        registrationDate: new Date("2020-07-15"),
        lastLogin: new Date("2023-09-28"),
        role: "user"
    },
    {
        id: 3,
        name: "Charlie Brown",
        email: "charlie.brown@example.com",
        age: 22,
        isActive: true,
        phone: "345-678-9012",
        address: "789 Pine St, Springfield",
        registrationDate: new Date("2022-01-10"),
        lastLogin: new Date("2023-10-02"),
        role: "user"
    },
    {
        id: 4,
        name: "David Wilson",
        email: "david.wilson@example.com",
        age: 45,
        isActive: true,
        phone: "456-789-0123",
        address: "321 Cedar St, Springfield",
        registrationDate: new Date("2019-03-20"),
        lastLogin: new Date("2023-09-30"),
        role: "moderator"
    },
    {
        id: 5,
        name: "Eva Adams",
        email: "eva.adams@example.com",
        age: 31,
        isActive: false,
        phone: "567-890-1234",
        address: "654 Birch St, Springfield",
        registrationDate: new Date("2020-11-05"),
        lastLogin: new Date("2023-09-20"),
        role: "user"
    },
    {
        id: 6,
        name: "Fiona Green",
        email: "fiona.green@example.com",
        age: 29,
        isActive: true,
        phone: "678-901-2345",
        address: "987 Spruce St, Springfield",
        registrationDate: new Date("2021-08-15"),
        lastLogin: new Date("2023-10-01"),
        role: "admin"
    },
    {
        id: 7,
        name: "George Hall",
        email: "george.hall@example.com",
        age: 40,
        isActive: true,
        phone: "789-012-3456",
        address: "135 Willow St, Springfield",
        registrationDate: new Date("2018-02-10"),
        lastLogin: new Date("2023-09-25"),
        role: "user"
    },
    {
        id: 8,
        name: "Hannah Baker",
        email: "hannah.baker@example.com",
        age: 26,
        isActive: false,
        phone: "890-123-4567",
        address: "246 Elm St, Springfield",
        registrationDate: new Date("2021-05-03"),
        lastLogin: new Date("2023-08-15"),
        role: "user"
    },
    {
        id: 9,
        name: "Ian Scott",
        email: "ian.scott@example.com",
        age: 36,
        isActive: true,
        phone: "901-234-5678",
        address: "357 Ash St, Springfield",
        registrationDate: new Date("2020-12-22"),
        lastLogin: new Date("2023-10-02"),
        role: "user"
    },
    {
        id: 10,
        name: "Julia Evans",
        email: "julia.evans@example.com",
        age: 24,
        isActive: true,
        phone: "012-345-6789",
        address: "468 Fir St, Springfield",
        registrationDate: new Date("2022-03-30"),
        lastLogin: new Date("2023-09-29"),
        role: "moderator"
    },
];