export const data = [
    {
        id: 1,
        name: "Alice Smith",
        email: "alice.smith@example.com",
        age: 28,
        isActive: true,
        phone: "123-456-7890",
        address: "123 Maple St, Springfield",
        registrationDate: new Date("2021-06-01"),
        lastLogin: new Date("2023-10-01"),
        role: "admin"
    },
    {
        id: 2,
        name: "Bob Johnson",
        email: "bob.johnson@example.com",
        age: 34,
        isActive: false,
        phone: "234-567-8901",
        address: "456 Oak St, Springfield",
        registrationDate: new Date("2020-07-15"),
        lastLogin: new Date("2023-09-28"),
        role: "user"
    },
    {
        id: 3,
        name: "Charlie Brown",
        email: "charlie.brown@example.com",
        age: 22,
        isActive: true,
        phone: "345-678-9012",
        address: "789 Pine St, Springfield",
        registrationDate: new Date("2022-01-10"),
        lastLogin: new Date("2023-10-02"),
        role: "user"
    },
    {
        id: 4,
        name: "David Wilson",
        email: "david.wilson@example.com",
        age: 45,
        isActive: true,
        phone: "456-789-0123",
        address: "321 Cedar St, Springfield",
        registrationDate: new Date("2019-03-20"),
        lastLogin: new Date("2023-09-30"),
        role: "moderator"
    },
    {
        id: 5,
        name: "Eva Adams",
        email: "eva.adams@example.com",
        age: 31,
        isActive: false,
        phone: "567-890-1234",
        address: "654 Birch St, Springfield",
        registrationDate: new Date("2020-11-05"),
        lastLogin: new Date("2023-09-20"),
        role: "user"
    },
    {
        id: 6,
        name: "Fiona Green",
        email: "fiona.green@example.com",
        age: 29,
        isActive: true,
        phone: "678-901-2345",
        address: "987 Spruce St, Springfield",
        registrationDate: new Date("2021-08-15"),
        lastLogin: new Date("2023-10-01"),
        role: "admin"
    },
    {
        id: 7,
        name: "George Hall",
        email: "george.hall@example.com",
        age: 40,
        isActive: true,
        phone: "789-012-3456",
        address: "135 Willow St, Springfield",
        registrationDate: new Date("2018-02-10"),
        lastLogin: new Date("2023-09-25"),
        role: "user"
    },
    {
        id: 8,
        name: "Hannah Baker",
        email: "hannah.baker@example.com",
        age: 26,
        isActive: false,
        phone: "890-123-4567",
        address: "246 Elm St, Springfield",
        registrationDate: new Date("2021-05-03"),
        lastLogin: new Date("2023-08-15"),
        role: "user"
    },
    {
        id: 9,
        name: "Ian Scott",
        email: "ian.scott@example.com",
        age: 36,
        isActive: true,
        phone: "901-234-5678",
        address: "357 Ash St, Springfield",
        registrationDate: new Date("2020-12-22"),
        lastLogin: new Date("2023-10-02"),
        role: "user"
    },
    {
        id: 10,
        name: "Julia Evans",
        email: "julia.evans@example.com",
        age: 24,
        isActive: true,
        phone: "012-345-6789",
        address: "468 Fir St, Springfield",
        registrationDate: new Date("2022-03-30"),
        lastLogin: new Date("2023-09-29"),
        role: "moderator"
    },
    {
        id: 11,
        name: "John Doe",
        email: "john.doe@example.com",
        age: 28,
        isActive: true,
        phone: "555-123-4567",
        address: "123 Maple St, Springfield",
        registrationDate: new Date("2020-01-01"),
        lastLogin: new Date("2023-10-10"),
        role: "admin"
    },
    {
        id: 12,
        name: "Jane Smith",
        email: "jane.smith@example.com",
        age: 34,
        isActive: false,
        phone: "555-234-5678",
        address: "234 Oak St, Springfield",
        registrationDate: new Date("2019-05-21"),
        lastLogin: new Date("2023-10-09"),
        role: "user"
    },
    {
        id: 13,
        name: "Sam Brown",
        email: "sam.brown@example.com",
        age: 40,
        isActive: true,
        phone: "555-345-6789",
        address: "345 Pine St, Springfield",
        registrationDate: new Date("2021-03-15"),
        lastLogin: new Date("2023-10-08"),
        role: "moderator"
    },
    {
        id: 14,
        name: "Emily White",
        email: "emily.white@example.com",
        age: 26,
        isActive: false,
        phone: "555-456-7890",
        address: "456 Birch St, Springfield",
        registrationDate: new Date("2022-07-10"),
        lastLogin: new Date("2023-10-07"),
        role: "user"
    },
    {
        id: 15,
        name: "Chris Green",
        email: "chris.green@example.com",
        age: 30,
        isActive: true,
        phone: "555-567-8901",
        address: "567 Cedar St, Springfield",
        registrationDate: new Date("2020-11-05"),
        lastLogin: new Date("2023-10-06"),
        role: "admin"
    },
    {
        id: 16,
        name: "Natalie Black",
        email: "natalie.black@example.com",
        age: 22,
        isActive: true,
        phone: "555-678-9012",
        address: "678 Elm St, Springfield",
        registrationDate: new Date("2021-09-20"),
        lastLogin: new Date("2023-10-05"),
        role: "user"
    },
    {
        id: 17,
        name: "Michael Blue",
        email: "michael.blue@example.com",
        age: 35,
        isActive: false,
        phone: "555-789-0123",
        address: "789 Spruce St, Springfield",
        registrationDate: new Date("2019-12-30"),
        lastLogin: new Date("2023-10-04"),
        role: "moderator"
    },
    {
        id: 18,
        name: "Linda Red",
        email: "linda.red@example.com",
        age: 29,
        isActive: true,
        phone: "555-890-1234",
        address: "890 Poplar St, Springfield",
        registrationDate: new Date("2020-04-15"),
        lastLogin: new Date("2023-10-03"),
        role: "user"
    },
    {
        id: 19,
        name: "Robert Yellow",
        email: "robert.yellow@example.com",
        age: 33,
        isActive: false,
        phone: "555-901-2345",
        address: "901 Ash St, Springfield",
        registrationDate: new Date("2021-01-25"),
        lastLogin: new Date("2023-10-02"),
        role: "admin"
    },
    {
        id: 20,
        name: "Julia Evans",
        email: "julia.evans@example.com",
        age: 24,
        isActive: true,
        phone: "012-345-6789",
        address: "468 Fir St, Springfield",
        registrationDate: new Date("2022-03-30"),
        lastLogin: new Date("2023-09-29"),
        role: "moderator"
    },

    {
        id: 21,
        name: "Alice Johnson",
        email: "alice.johnson@example.com",
        age: 29,
        isActive: true,
        phone: "987-654-3210",
        address: "123 Maple St, Springfield",
        registrationDate: new Date("2022-01-12"),
        lastLogin: new Date("2023-10-01"),
        role: "admin"
    },
    {
        id: 22,
        name: "Bob Smith",
        email: "bob.smith@example.com",
        age: 35,
        isActive: true,
        phone: "876-543-2109",
        address: "456 Oak St, Springfield",
        registrationDate: new Date("2022-02-15"),
        lastLogin: new Date("2023-09-25"),
        role: "user"
    },
    {
        id: 23,
        name: "Charlie Brown",
        email: "charlie.brown@example.com",
        age: 28,
        isActive: false,
        phone: "765-432-1098",
        address: "789 Pine St, Springfield",
        registrationDate: new Date("2022-03-10"),
        lastLogin: new Date("2023-08-30"),
        role: "moderator"
    },
    {
        id: 24,
        name: "Daisy Miller",
        email: "daisy.miller@example.com",
        age: 22,
        isActive: true,
        phone: "654-321-0987",
        address: "101 Birch St, Springfield",
        registrationDate: new Date("2022-04-05"),
        lastLogin: new Date("2023-09-15"),
        role: "guest"
    },
    {
        id: 25,
        name: "Ethan Williams",
        email: "ethan.williams@example.com",
        age: 34,
        isActive: true,
        phone: "543-210-9876",
        address: "202 Cedar St, Springfield",
        registrationDate: new Date("2022-05-20"),
        lastLogin: new Date("2023-10-01"),
        role: "user"
    },
    {
        id: 26,
        name: "Fiona Davis",
        email: "fiona.davis@example.com",
        age: 27,
        isActive: false,
        phone: "432-109-8765",
        address: "303 Elm St, Springfield",
        registrationDate: new Date("2022-06-14"),
        lastLogin: new Date("2023-09-12"),
        role: "admin"
    },
    {
        id: 27,
        name: "George Harris",
        email: "george.harris@example.com",
        age: 31,
        isActive: true,
        phone: "321-098-7654",
        address: "404 Spruce St, Springfield",
        registrationDate: new Date("2022-07-19"),
        lastLogin: new Date("2023-09-09"),
        role: "user"
    },
    {
        id: 28,
        name: "Hannah Clark",
        email: "hannah.clark@example.com",
        age: 26,
        isActive: false,
        phone: "210-987-6543",
        address: "505 Poplar St, Springfield",
        registrationDate: new Date("2022-08-22"),
        lastLogin: new Date("2023-10-02"),
        role: "moderator"
    },
    {
        id: 29,
        name: "Isaac Wright",
        email: "isaac.wright@example.com",
        age: 23,
        isActive: true,
        phone: "109-876-5432",
        address: "606 Willow St, Springfield",
        registrationDate: new Date("2022-09-13"),
        lastLogin: new Date("2023-09-14"),
        role: "guest"
    },
    {
        id: 30,
        name: "Jasmine Taylor",
        email: "jasmine.taylor@example.com",
        age: 32,
        isActive: true,
        phone: "098-765-4321",
        address: "707 Ash St, Springfield",
        registrationDate: new Date("2022-10-17"),
        lastLogin: new Date("2023-10-03"),
        role: "admin"
    },
    {
        id: 31,
        name: "Kyle Lee",
        email: "kyle.lee@example.com",
        age: 30,
        isActive: false,
        phone: "987-654-3210",
        address: "808 Redwood St, Springfield",
        registrationDate: new Date("2022-11-25"),
        lastLogin: new Date("2023-09-28"),
        role: "user"
    },
    {
        id: 32,
        name: "Lily Green",
        email: "lily.green@example.com",
        age: 28,
        isActive: true,
        phone: "876-543-2109",
        address: "909 Sequoia St, Springfield",
        registrationDate: new Date("2022-12-05"),
        lastLogin: new Date("2023-10-01"),
        role: "moderator"
    },
    {
        id: 33,
        name: "Mason Allen",
        email: "mason.allen@example.com",
        age: 25,
        isActive: true,
        phone: "765-432-1098",
        address: "1010 Fir St, Springfield",
        registrationDate: new Date("2023-01-14"),
        lastLogin: new Date("2023-09-30"),
        role: "guest"
    },
    {
        id: 34,
        name: "Nora Walker",
        email: "nora.walker@example.com",
        age: 29,
        isActive: true,
        phone: "654-321-0987",
        address: "1111 Oak St, Springfield",
        registrationDate: new Date("2023-02-25"),
        lastLogin: new Date("2023-09-25"),
        role: "admin"
    },
    {
        id: 35,
        name: "Oscar Young",
        email: "oscar.young@example.com",
        age: 33,
        isActive: false,
        phone: "543-210-9876",
        address: "1212 Pine St, Springfield",
        registrationDate: new Date("2023-03-14"),
        lastLogin: new Date("2023-10-01"),
        role: "user"
    },
    {
        id: 36,
        name: "Penny Brooks",
        email: "penny.brooks@example.com",
        age: 27,
        isActive: true,
        phone: "432-109-8765",
        address: "1313 Maple St, Springfield",
        registrationDate: new Date("2023-04-23"),
        lastLogin: new Date("2023-09-21"),
        role: "moderator"
    },
    {
        id: 37,
        name: "Quincy Edwards",
        email: "quincy.edwards@example.com",
        age: 24,
        isActive: true,
        phone: "321-098-7654",
        address: "1414 Birch St, Springfield",
        registrationDate: new Date("2023-05-12"),
        lastLogin: new Date("2023-10-01"),
        role: "guest"
    },
    {
        id: 38,
        name: "Rachel Carter",
        email: "rachel.carter@example.com",
        age: 31,
        isActive: false,
        phone: "210-987-6543",
        address: "1515 Cedar St, Springfield",
        registrationDate: new Date("2023-06-19"),
        lastLogin: new Date("2023-09-17"),
        role: "admin"
    },
    {
        id: 39,
        name: "Samuel Davis",
        email: "samuel.davis@example.com",
        age: 30,
        isActive: true,
        phone: "109-876-5432",
        address: "1616 Elm St, Springfield",
        registrationDate: new Date("2023-07-10"),
        lastLogin: new Date("2023-10-01"),
        role: "user"
    },
    {
        id: 40,
        name: "Tina Martinez",
        email: "tina.martinez@example.com",
        age: 26,
        isActive: false,
        phone: "098-765-4321",
        address: "1717 Redwood St, Springfield",
        registrationDate: new Date("2023-08-28"),
        lastLogin: new Date("2023-10-02"),
        role: "moderator"
    },
];
